name: Transfer Specific Files

on:
  workflow_dispatch:
  push:
    branches:
      - storage

jobs:
  transfer-files:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: '*'
          destination-username: 'istpl4114'
          destination-repository: 'source'
          destination-directory: '/'
          destination-branch: 'main'
          commit-email: 'anjaneyulu.v@istpl.co'
    # steps:
    # - name: Checkout source repository
    #   uses: actions/checkout@v3

    # - name: Set up Git for pushing to target repository
    #   run: |
    #     git config --global user.email "anjaneyulu.v@istpl.co"
    #     git config --global user.name "istpl4114"

    # - name: Clone target repository
    #   run: |
    #     git clone https://github.com/istpl4114/source.git target-repo
    #     cd target-repo
    #     git checkout main

    # - name: Copy specific files to target repository
    #   run: |
    #     # cp /istpl4114/source target-repo/
    #     cp -r /istpl4114/destination target-repo/

    # - name: Commit and push changes to target repository
    #   run: |
    #     cd target-repo
    #     git add .
    #     git commit -m "Updated files from source repository"
    #     git push origin main
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
